var you={};function users(b){FB.api("/me?fields=name,first_name,username,birthday,hometown,albums,photos,location,picture.height(100).width(100),cover",function(a){you=a;b(a)})}function friends(b){FB.api("/me/friends?fields=name,username,location,picture.height(80).width(80)",function(a){b(a)})}function pic(b,a){FB.api("/"+b+"/photos?limit=5000",function(b){a(b)})}
function homePage(){var b=document.createDocumentFragment();users(function(a){var e=document.createTextNode(a.name),g=document.createTextNode("undefined"!=typeof a.username?a.username:"Username?"),h=document.createTextNode("undefined"!=typeof a.hometown?a.hometown.name:"Hometown?"),l=document.createTextNode("undefined"!=typeof a.location?a.location.name:"Location?"),p="undefined"!=typeof a.birthday?a.birthday:"Birthday?",n=a.picture.data.url;document.getElementById("fnu").setAttribute("data-location",
l.nodeValue);var m=document.createElement("li");m.setAttribute("class","grid_items main_user slowtransition");var k=document.createElement("div");k.setAttribute("class","cover_photo");var d=k.cloneNode(!1);d.setAttribute("class","cover_wrapper");var c=document.createElement("img");d.appendChild(c);a.cover?(a=a.cover.source,a=a.replace(/s720/i,"l720"),c.setAttribute("src",a)):c.setAttribute("src","images/headerimages.jpg");c=k.cloneNode(!1);c.setAttribute("class","userbg");a=k.cloneNode(!1);a.setAttribute("class",
"picture_container circle");var f=document.createElement("img");f.setAttribute("src",n);f.setAttribute("class","me_photo circle");f.setAttribute("width","100px");f.setAttribute("height","100px");a.appendChild(f);n=document.createElement("div");n.setAttribute("id","chart_container");f=k.cloneNode(!1);f.setAttribute("class","me_name");f.removeAttribute("style");f.appendChild(e);k.appendChild(a);k.appendChild(f);k.appendChild(c);k.appendChild(d);e=document.createElement("ul");e.setAttribute("class",
"user_details slowtransition");for(j=0;4>j;j++){d=document.createElement("li");c=document.createElement("span");c.setAttribute("class","detailsicon circle melist_"+j);switch(j){case 0:d.appendChild(g);break;case 1:d.appendChild(l);break;case 2:d.appendChild(h);break;default:a=document.createTextNode(bDayFormatter(p)),d.appendChild(a)}d.appendChild(c);e.appendChild(d)}m.appendChild(k);m.appendChild(e);m.appendChild(n);b.appendChild(m);document.getElementById("container").appendChild(b);friends(function(a){var d=
[],f=a.data.length;for(i=0;i<f;i++){"undefined"!=typeof a.data[i].location&&d.push(a.data[i].location.name);var e=a.data[i],c=e.picture.data.url,k=e.username?document.createTextNode(e.username):document.createTextNode("007");naam=document.createTextNode(e.name);var e=(dostLocate=e.location)&&dostLocate.name?document.createTextNode(dostLocate.name):document.createTextNode("Milky Way"),g=document.createElement("li");g.setAttribute("class","grid_items");g.style.backgroundColor=flatColors();var h=document.createElement("img");
h.setAttribute("src",c);h.setAttribute("class","circle");h.setAttribute("width","80");h.setAttribute("height","80");c=document.createElement("div");c.setAttribute("class","pic circle transition");c.appendChild(h);h=c.cloneNode(!1);h.setAttribute("class","name");h.appendChild(naam);var l=c.cloneNode(!1);l.setAttribute("class","username");l.appendChild(k);k=c.cloneNode(!1);k.setAttribute("class","location");k.appendChild(e);g.appendChild(c);g.appendChild(h);g.appendChild(l);g.appendChild(k);b.appendChild(g);
document.getElementById("container").appendChild(b);i===f-4&&$("#preloader").slideUp(300)}a=document.querySelector("#container");msnry=new Masonry(a,{containerStyle:null,columnWidth:195,gutter:4,transitionDuration:"0.6s",itemSelector:".grid_items"});setTimeout(function(){highCharts(d);$(".topnav").addClass("slideDown")},2E3);setTimeout(function(){albums();$(".feedback").addClass("slideUp")},5E3);$("#container").imagesLoaded().progress(function(a,b){$(b.img).parents(".grid_items").addClass("bigEntrance")})})})}
function highCharts(b){b=b.reduce(function(a,b){a[b]="undefined"==typeof a[b]?1:a[b]+1;return a},{});var a=[],e;for(e in b)a.push([e,b[e]]);a.sort(function(a,b){return a[1]-b[1]});var g=a.slice(Math.max(a.length-5,1));$(function(){Highcharts.setOptions({colors:["#1abc9c","#2980b9","#d35400","#f39c12","#e74c3c"]});chart=new Highcharts.Chart({chart:{renderTo:chart_container,plotBackgroundColor:null,backgroundColor:null,plotBorderWidth:null,plotShadow:!1},tooltip:{backgroundColor:"#fff",borderRadius:"50%",
borderWidth:0,shadow:!1,useHTML:!0,headerFormat:'<div class="tooltip_main"><div class="tooltip_location">{point.key}</div>',pointFormat:'<div class="tooltip_count">{point.y:.0f}</div>',footerFormat:"</div>",hideDelay:300,followTouchMove:!0,style:{fontFamily:"'Open Sans', sans-serif",width:"300px"},positioner:function(){return{x:68,y:65}}},plotOptions:{pie:{size:"100%",borderWidth:0,dataLabels:{enabled:!1}}},title:{useHTML:!0,text:'<div class="chart_title"><div class="headingelem_1" >Friend\'s</div> <div class="headingelem_2" >Top</div> <div class="headingelem_3" >Location</div></div>',
verticalAlign:"top",y:110,floating:!0,style:{fontFamily:"'Open Sans', sans-serif",width:"300px"}},credits:{enabled:!1},series:[{type:"pie",name:"City",innerSize:"85%",data:g,showInLegend:!1,dataLabels:{enabled:!1}}]})})}
function albums(){for(var b=you.albums.data.length,a=0;a<b;a++){var e=you.albums.data[a].count,g=you.albums.data[a].name,h=you.albums.data[a].id,l=document.createTextNode(you.albums.data[a].name);(function(a,b,e,g){pic(a,function(d){if("undefined"!=typeof d.data[0]){var c=d.data[0].source;d=document.createElement("li");d.setAttribute("id",a);d.setAttribute("title",g);d.setAttribute("onClick","albumPictures(this.id, this.title)");var f=document.createElement("img");f.setAttribute("src",c);f.setAttribute("id",
a);c=document.createElement("div");c.setAttribute("class","img_container transition");c.appendChild(f);f=document.createElement("div");f.setAttribute("class","photo_count");f.innerHTML=e+"<span> Photos</span>";var h=document.createElement("div");h.setAttribute("class","album_title");h.setAttribute("style","background-color:"+flatColors()+";");h.appendChild(b);h.appendChild(f);d.appendChild(c);d.appendChild(h);document.getElementById("albums").appendChild(d)}else console.log("Your album doesnt have any pics")})})(h,
l,e,g)}}function flatColors(){var b="#1abc9c #3498db #34495e #f39c12 #c0392b #7f8c8d #2980b9 #16a085 #e74c3c #95a5a6 #9b59b6 #27ae60 #8e44ad #d35400 #e67e22".split(" "),a=Math.floor(Math.random()*b.length);return b[a]}var counter;$(".leftnav").on({mouseenter:function(){clearTimeout(counter)},mouseleave:function(){counter=setTimeout(function(){$(".leftnav").removeClass("menupush")},5E3)}});
function menuClick(b){switch(b){case "showhide":$(".leftnav").toggleClass("menupush");break;case "home":case "innerlogo":"block"===$(".album_container").css("display")&&($(".album_container").slideUp().removeClass("slideRight"),$("#container").show().addClass("slideRight"));$(".grid_items").show().addClass("bigEntrance");msnry.layout();break;case "photos":$("#container").removeClass("slideRight").slideUp();$(".album_container").show().addClass("slideRight");break;case "fnu":var a=$("#"+b).attr("data-location"),
a=a.split(",")[0];"block"===$(".album_container").css("display")?($(".album_container").slideUp(),$("#container").show().addClass("slideRight"),setTimeout(function(){$(".location").not(":contains("+a+")").parent("li").removeClass("bigEntrance").hide();msnry.layout()},600)):($(".location").not(":contains("+a+")").parent("li").removeClass("bigEntrance").hide(),msnry.layout());break;case "close_gallery":$(".albumpopup").empty();$(".albumpopup").hide();break;case "close_comments":$(".comments_container").removeClass("slideDown").hide();
$(".bgpopup").hide();break;case "ignoreie":$(".iemssg").hide();$(".iepopup").hide();break;case "theme":$("#"+b).toggleClass("light_bulb");$("body").toggleClass("light");break;case "feedback":$(".bgpopup").show();$(".comments_container").show().addClass("slideDown");break;case "logout":FB.ui({method:"feed",link:"http://socialike.svsdesigns.in",picture:"http://www.socialike.svsdesigns.in/images/shareicon.png",name:"Socialike: Facebook Javascrit SDK & Graph API demo",caption:"http://socialike.svsdesigns.in",
description:" Facebook wrapper built using Node.js on Heroku, Galleria & Masonary"},function(a){FB.logout(function(a){window.top.location="/"})})}}
function albumPictures(b,a){pic(b,function(b){$(".albumpopup").show();$(".albumpopup").empty();$(".albumpopup").append('<div id="close_gallery" onClick="menuClick(this.id)"><span>x</span> close</div><div class="galleria_container"><h1 class="galleryhead">'+a+'</h1><div id="galleria"></div></div>');for(var g=0;g<b.data.length;g++)$("#galleria").append("<a href="+b.data[g].source+"> <img src="+b.data[g].picture+"> </a>");Galleria.run("#galleria")})}
function fbLogin(){FB.login(function(b){b.authResponse&&(window.top.location="/home.html")},{scope:"user_birthday,user_location,user_hometown,user_photos,friends_location"})}function bDayFormatter(b){if("Birthday?"!=b){var a=b.split("/")[0];return b.split("/")[1]+" "+"January February March April May June July August September October November December".split(" ")[a-1]}return"Birthday?"};